---
title: "Zapiski za izpit"
subtitle: "Analiza 3 2024/25"
author: "Jan Panjan"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
    toc_depth: 3
---

> > *Zapiski so večinoma iz knjige "Metrični prostori, Jože Vrabec"*

# Metrični prostori

## Definicija metrike

Naj bo $M \not = \emptyset$. Metrika na $M$ je realna funkcija $d$ dveh spremenljivk na $M$, ki ustreza pogojem:

a) $d(x,y) \geq 0$
b) $d(x,y) = 0 \implies x = y$
c) $d(x,y) = d(y,x)$
d) $d(x,z) \leq d(x,y) + d(y,z)$

V jeziku teorije množic je metrika preslikava $d: M \times M \rightarrow \mathbb{R}$. Slika $d(x,y)$ je
razdalja elementov $x$ in $y$. Neenakost $d(x,z) \leq d(x,y) + d(y,z)$ treh točk $x,y,z \in M$  imenujemo
**trikotniška neenenakost**. Iz te neenačbe velja tudi $| d(x,z) - d(y,z) | \leq d(x,y)$.

*Dokaz iz lastnosti (d)*:

$$
\begin{aligned}
d(x,z) \leq &d(x,y) + d(y,z) \\
d(x,z) - d(y,z) \leq &d(x,y) \\
- (d(x,z) - d(y,z)) \leq &d(x,y) \\
\implies | d(x,z) - d(y,z) | \leq &d(x,y) \quad \square
\end{aligned}
$$

## Definicija metričnega prostora

Množico $M \not = \emptyset$ skupaj z izbrano metriko $d$ na $M$ (torej par $(M,d)$ ) imenujemo **metrični prostor**.
Če vzamemo neko drugo metriko $d'$ je potem $(M, d')$ nek drug metrični prostor.

Osnovni zgledi metričnega prostora so premice ($\mathbb{R}$), ravnine ($\mathbb{R}^2$) in prostori ($\mathbb{R}^3$)
z običajno metriko, definirana:

> $d(x,y) = |y-x|$ za $x,y \in \mathbb{R}$
>
> $d(x,y) = \sqrt((y_1 - y_2) + (x_1 - x_2))$ za $(x_1,x_2),(y_1,y_2) \in \mathbb{R}^2$
>
> podobno za $\mathbb{R}^3$ ...

Množice $\mathbb{R}, \mathbb{R}^2, \mathbb{R}^3$ so vektorski prostori, zato seštevamo in s skalarjem množimo po
komponentah. Iz lastnosti $x-y = (x_1 - y_1, x_2 - y_2)$ velja:

$$
d(x,y) = d(0, y-x)
$$

To pomeni, da je razdalja med točkama $x$ in $y$ enaka razdalji od izhodišča do vektorja $y-x$. Metrika za katero
velja ta lastnost je popolnoma določena, če za vsako točko navedemo njeno razdaljo od točke 0. To razdaljo bomo
v splošnih prostorih s to lastnostjo imenovali...

## Norma

Naj bo $X$ nek realen ali kompleksen vektorski prostor. **Norma** na $X$ je funkcija $||.||: X \rightarrow \mathbb{R}$,
ki ustreza pogojem:

a) $||x|| \geq 0$
b) $||x|| = 0 \implies x = 0$
c) $||\lambda x|| = |\lambda| \cdot ||x||$
d) $||x+y|| \leq ||x|| + ||y||$

Prostor skupaj z normo na njem imenujemo **normiran vektorski prostor** (torej $(X, ||.||)$). Tudi tu je lastnost
(d) imenovana trikotniška neenakost in tudi iz nje lahko izpeljemo novo neenakost:

$$
\begin{aligned}
| \ ||x|| - ||y|| \ | \leq || x - y ||
\end{aligned}
$$

Če je $X$ normiran vektorski prostor, je s formulo $d(x,y) = || y-x ||$ definirana metrika na $X$. Iz formule sledi
lastnost $||x|| = d(0,x)$, zato je formula indentična kot tista od prej (glej Cauchy-Schwarz-Bunjakovski neenačbo za
dokaz).

Torej *vsak normiran prostor je metrični prostor*. Prav tako so zgoraj omenjeni prostori $\mathbb{R}$,
$\mathbb{R}^2$, $\mathbb{R}^3$ tudi normirani prostori. Norme v njih so definirane tako:

> $||x|| = |x|$
>
> $||x|| = \sqrt(x_1^2 + x_2^2)$
>
> $||x|| = \sqrt(x_1^2+x_2^2+x_3^2$

Očitno je da ustrezajo vsem pogojem, vendar je za $\mathbb{R}^2$ in $\mathbb{R}^3$ težje dokazati
trikotniško neenakost. **Poglej si to!!!**

Pri vektorjih lahko računamo dolžine vektorjev s skalarnim produktom. Dolžina vektorja $\vec v$ je kvadratni
koren skalarnega produkta $\vec v \cdot \vec v$. To bomo posplošili in pokazali, da vsak skalarni produkt na
nekem vektorskem prostoru $X$ porodi normo na $X$. Obstajajo tudi norme, ki ne izhajajo iz nobenega skalarnega
produkta.

## Skalarni produkt

**Skalarni produkt** na realnem vektorskem prostoru $X$ je funkcija $\langle .,. \rangle :X\times X \rightarrow \mathbb{R}$
z lastnostmi:

a) $\langle x,x \rangle \geq 0$

b) $\langle x,x \rangle = 0 \implies x = 0$

c) $\langle \lambda x + \mu y, z \rangle = \lambda \langle x,z \rangle + \lambda \langle y,z \rangle$

d) $\langle y,x \rangle = \langle x,y \rangle$

Realen vektorski prostor skupaj s skalarnim produktom na njem imenujemo **realen unitaren vektorski prostor*.
Lastnost (c) se imenuje **linearnost v prvem faktorju**, lastnost (d) **simetričnost** (ki zagotavlja tudi
linearnost v drugem faktorju) ter (a) in (b) **pozitivna definitnost**.

Skalarni produkt na realnem linearnem prostoru $X$ je *pozitivno definiten bilinearen funkcional na* $X$
Preprosto je definiran na prostorih $\mathbb{R}$ in $\mathbb{R}^2$; tu je primer za $\mathbb{R}^3$:

$$
\langle x,y \rangle  = x_1 y_1 + x_2y_2 + x_3y_3
$$

Če je $X$ unitaren prostor, je s formulo $||x||: \sqrt(\langle x,x \rangle )$ definirana norma na $X$. Zdaj sta torej definirani
zgornji funkciji norme na $\mathbb{R}^2$ in $\mathbb{R}^3$.

## Cauchy-Schwarz-Bunjakovski neenačba

V vsakem unitarnem prostoru velja za poljubna vektorja $x$ in $y$ Cauchy-Schwarz-Bunjakovski neenakost, ki izgleda
tako:

$$
\begin{aligned}
\| \langle x,y \rangle |^2 &\leq \langle x,x \rangle \cdot \langle y,y \rangle \\
\| \langle x,y \rangle | &\leq \langle x \rangle \cdot \langle y \rangle
\end{aligned}
$$

Neenakost je posplošitev znane neenakosti $|\vec a \cdot \vec b| \leq |\vec a| \cdot |\vec b|$, ki velja za
geometrične vektorje. V kolikor sta $x$ in $y$ linearno neodvisna, velja v zgornji neenačbi strogi neenačaj.

---

### Note glede kompleksnih prostorov

Velja lastnost $\langle x,y \rangle  = \overline{\langle y,x \rangle}$. Skalarni produkt na kompleksnem prostoru
tako ustreza pogojem (a), (b), (c) in namesto (d) tej lastnosti. Primer je naslednja lastnost, ki je komplementarno
pogoju (c):

$$
\langle z, \lambda x + \mu y \rangle = \bar \lambda \langle z,x \rangle + \bar \mu \langle z,y \rangle
$$

To res velja s pomočjo pogojev (c) in (d) iz definicije skalarnega produkta in zgornje lastnosti.

$$
\begin{aligned}
\langle z, \lambda x + \mu y \rangle &= \overline{ \langle \lambda x + \mu y, z \rangle } \\
&= \overline{ \lambda \langle x,z \rangle + \mu \langle y,z \rangle } \\
&= \bar \lambda \overline{ \langle x,z \rangle } + \bar \mu \overline{ \langle y,z \rangle } \\
&= \bar \lambda \langle z,x \rangle + \bar \mu \langle z,y \rangle \quad \square
\end{aligned}
$$

---

*Dokaz za Cauchy-Schwarz-Bunjakovski neenačbo*: če je $y=0$, potem je neenakost gotovo pravilna in vektorja $x$ in $y$ sta tudi linearno odvisna
(${| \langle x,0 \rangle |}^2 \leq \langle x,x \rangle \cdot \langle 0,0 \rangle = 0$). Privzamemo, da
$y \not = 0$, zato velja $\langle y,y \rangle > 0$ po (a) in (b). Za poljubna skalarja $\lambda$ in $\mu$
velja tedaj:

$$
\langle \lambda x + \mu y, \lambda x + \mu y \rangle = | \lambda |^2 \cdot \langle x,x \rangle + \lambda \bar \mu \langle x,y \rangle + \bar \lambda \mu \langle y,x \rangle + | \mu |^2 \langle y,y \rangle
$$

Zdaj naj bo $\lambda = \langle y,y \rangle$ in $\mu = - \langle x,y \rangle$. Upoštevamo, da je
$\lambda = \bar \lambda$ in $\langle y,x \rangle = \langle x,y \rangle$. Na desni strani enačbe dobimo zdaj:

$$
\begin{aligned}
{\langle y,y \rangle}^2 \cdot \langle x,x \rangle -
	\langle y,y \rangle \cdot {| \langle x,y \rangle |}^2 -
	\langle y,y \rangle \cdot {| \langle x,y \rangle |}^2 +
	{| \langle x,y \rangle |}^2 \cdot \langle y,y \rangle \\
= \langle y,y \rangle \cdot \left( \langle x,x \rangle \cdot \langle y,y \rangle - {| \langle x,y \rangle |}^2 \right)
\end{aligned}
$$

Leva stran prve enakosti je nenegativna zaradi lastnosti (a). V primeru, da sta $x$ $y$ linearno odvisna je pozitivna,
saj je $\lambda \not = 0 \implies \lambda x + \mu y \not = 0$, kar dokaže Cauchy-Schwarz-Bunjakovski neenačbo. $\square$

### Dokaz trikotniške neenakosti

S pomočjo teh lastnosti lahko zdaj dokažemo lastnost (d) trikotniške neenakosti iz izreka o normi na unitarnem
prostoru $X$. Iz definicije norme in lastnosti (c) iz definicije skalarnega produkta sledi:

$$
\begin{aligned}
\lVert{ x+y \rVert} &= \langle x+y, x+y \rangle \\
                    &= \langle x,x \rangle + \langle x,y \rangle + \langle y,x \rangle + \langle y,y \rangle \\
										&\leq \lVert{ x \rVert}^2 + | \langle x,y \rangle | + \langle y,x \rangle + \lVert{ y \rVert}^2 \\
										&= \lVert{ x \rVert}^2 + \lVert{ x \rVert} \cdot \lVert{ y \rVert} + \lVert{ y \rVert} \cdot \lVert{ x \rVert} + \lVert{ y \rVert}^2 \\
										&= \left( \lVert{ x \rVert} + \lVert{ y \rVert} \right)^2 \quad \square
\end{aligned}
$$

Če sta $x$ in $y$ linearno odvisna velja po definiciji Cauchy-Schwarz-Bunjakovski neenačbe
$\lVert{ x+y \rVert} < \lVert{ x \rVert} + \lVert{ y \rVert}$.

Po tej lemi velja, da **norma v takem prostoru ne izhaja iz skalarnega produkta** in poda potreben pogoj za to,
da je norma porojena s skalarnim produktom (torej, za tiste, ki to ne velja, so porojene iz skalarnega produkta?).

Prav tako velja, da v unitarnem prostoru **norma natanko določa skalarni produkt**. V poljubnem unitarnem
prostoru nad poljem skalarjev $\mathbb{F} = \mathbb{R}$ je:

$$
\langle x,y \rangle = \begin{cases}
\frac{\left( \lVert{ x+y \rVert}^2 - \lVert{ x-y \rVert}^2 \right)}{4} ; &\mathbb{F} = \mathbb{R} \\
\frac{\left( \lVert{ x+y \rVert}^2 - \lVert{ x-y \rVert}^2 \right)}{4} +
  \frac{\left( \lVert{ x+iy \rVert}^2 - \lVert{ x-iy \rVert}^2 \right)}{4} ; &\mathbb{F} = \mathbb{C} \\
\end{cases}
$$

Leva stran je skalarni produkt, na desni strani ga definira norma, right?

## Paralelogramska identiteta

V poljubnem unitarnem prostoru velja za poljubna elementa $x$ in $y$ Paralelogramska identiteta:

$$
\lVert{ x+y \rVert}^2 + \lVert{ x-y \rVert}^2 = 2 \left( \lVert{ x \rVert}^2 + \lVert{ y \rVert}^2 \right)
$$

*Dokaz*:

$$
\begin{aligned}
\lVert{ x+y \rVert}^2 + \lVert{ x-y \rVert}^2 &= \langle x+y, x+y \rangle + \langle x-y, x-y \rangle \\
&= \langle x,x \rangle + \langle x,y \rangle + \langle y,x \rangle + \langle y,y \rangle +
     \langle x,x \rangle + \langle x,-y \rangle + \langle -y,x \rangle + \langle y,y \rangle \\
&= \langle x,x \rangle + \langle x,y \rangle + \langle y,x \rangle + \langle y,y \rangle +
     \langle x,x \rangle - \langle x,y \rangle - \langle y,x \rangle + \langle y,y \rangle \\
&= \langle x,x \rangle + \langle y,y \rangle + \langle x,x \rangle + \langle y,y \rangle \\
&= \lVert{ x \rVert}^2 + \lVert{ y \rVert}^2 + \lVert{ x \rVert}^2 + \lVert{ y \rVert}^2 \\
&= 2 \left( \lVert{ x \rVert}^2 + \lVert{ y \rVert}^2 \right)
\end{aligned}
$$

V paralelogramski identiteti nastopa samo norma, zato ima smisel v nekem normiranem prostoru. Ne velja pa,
da je v njem tudi *pravilna*. Spodaj je dokazana samo za primer, ko izhaja iz skalarnega produkta, toda obstajajo
normirani prostori, kjer identiteta ne velja.

Iz zgornje trditve sledi, da **ti prostori niso unitarni** in da **njihove norme ne izjajo iz skalarnega produkta**.
Ta trditev podaja novi pogoj za to, da je norma porojena s skalarnim produktom.

## Ničelni skalarni produkt

Elementa $x$ in $y$ poljubnega unitarnega prostora $X$ imenujemo **pravokotna** oziroma **ortogonalna**, če je
$\langle x,y \rangle = 0$ in zato $\langle y,x \rangle = \overline{ \langle x,y \rangle } = 0$. Ta lastnost
implicira obstoj...

## Pitagorov izrek

Ker poljubna pravokotna vektorja $\vec a$ in $\vec b$ ležita na katetah pravokotnega trikotnita s hipotenuzo
$\vec a + \vec b$, razlaga Pitagorov izrek zvezo med dolžinami teh vektorjev. Preko norme definirano naslednjo
posplošitev:

> Če sta $x$ in $y$ pravokotna vektorja poljubnega unitarnega prostora, velja
> $\lVert{ x+y \rVert}^2 = \lVert{ x \rVert}^2 + \lVert{ y \rVert}^2$

*Dokaz*: velja $\langle x,y \rangle = \langle y,x \rangle = 0$, zato:

$$
\begin{aligned}
\lVert{ x+y \rVert}^2 &= \langle x+y, x+y \rangle \\
											&= \langle x,x \rangle + \langle x,y \rangle + \langle y,x \rangle + \langle y,y \rangle \\
											&= \lVert{ x \rVert}^2 + \lVert{ y \rVert}^2 \quad \square
\end{aligned}
$$

## Krogle v metričnih prostorih

Naj bo $M$ metrični prostor ter točka $a \in M$ in $r > 0$. Ločimo naslednje množice točk:

$$
\begin{aligned}
&K(a,r) = K_M(a,r) = \{ x \in M \ | d(a,x) < r \} \text{ odprta krogla (točke se dotikajo roba krogle)} \\
&\bar K(a,r) = \bar K_M (a,r) = \{ x \in M \ | d(a,x) \leq r \} \text{ zaprta krogla (točke se ne dotikajo roba)} \\
&S(a,r) = S_M(a,r) = \{ x \in M \ | d(a,x) = r \} \text{ sfera (samo rob/površina krogle)}
\end{aligned}
$$

Vse imajo središče v točki $a$ in polmer $r$ ter spadajo v metrični prostor $M$.

### Enotska krogla

Če poznamo eno kroglo nekega normiranega prostora $X$, poznamo vse krogle. To je prikazano z naslednjim
primerom:

> Za poljubni točki $a$ in $b$ normiranega prostora $X$ in za poljubni pozitivni števili $r$ in $s$ je preslikava
> $f: X \rightarrow X$, definirana z $f(x)=(s/r)(x-a)+b$, bijekcija ter preslika
>
> - $a$ v $b$,
> - $K(a,r)$ na $K(b,s)$,
> - $\bar K(a,r)$ na $\bar K(b,s)$,
> - $S(a,r)$ na $S(b,s)$.

> *Dokaz*: Preslikava $f$ je očitno inverzna, saj je bijekcija, zato imamo za poljuben $x \in X$ naslednje ekvivalence:
>
> $$
> \begin{aligned}
x \in S(a,r) \iff &\lVert{ x-a \rVert} = r \\
             \iff &\lVert{ (s/r)(x-a) \rVert} = s \\
						 \iff &\lVert{ f(x) - b \rVert} = s \\
						 \iff &f(x) \in S(b,s) \quad \square
> \end{aligned}
> $$

Podoben sklep velja za odprte in zaprte krogle. Ker ima $f$ čisti "geometrični" pomen, sta si krogli $K(a,r)$ in
$K(b,s)$ (in ostale množice) povsem podobni v geometričnem pomenu besede. Velja namreč, da je $f$ sestavljena iz
preslikave

- $x \mapsto x-a$ oziroma translacije prostora $X$ za vektor $-a$
- $x \mapsto (s/r)x$ oziroma $(s/r)-$kratne povečave/pomanjšave prostora
- $x \mapsto x+b$ oziroma translacije prostora $X$ za vektor $b$

Torej res poznamo vse krogle, če poznamo eno in lahko vedno vzamemo enostavno kroglo oziroma tisto "navadno"
kroglo, da opišemo ostale. Krogli $K(0,1)$ rečemo **enotska krogla** (lahko je odprta, zaprta ali sfera). Ima
izhodišče v točki 0 in polmer 1.

Vseeno v splošnem metričnem prostoru ne velja, da so krogle z istimi središči in različnimi polmeri lahko v
čemerkoli podobni.

## Diameter

**Premer** ali diameter neprazne podmnožice $A$ metričnega prostora $M$ je
$\text{diam}A = sup \{ d(a,b) \ | a,b \in A \}$. Množica $A$ je omejena, če velja eno izmed:

- $A = \emptyset$
- $A < \infty$

**to si poglej v zvezku ker vem da maš iz predavanja**

## Odprte in zaprte množice

## Kompaktnost in povezanost

## Zaporedja v metričnih prostorih

## Cauchy-jeva zaporedja in polni prostori

## Zveznost in enakomerna zveznost

## Lastnosti zveznih preslikav

# Funkcije več realnih spremenljivk

## Zveznost

## Parcialna odvedljivost

## Diferencial preslikavce iz Rn v Rmo

## Jacobijeva matrika

## Verižno pravilo

# Višji parcialni odvodi

## Taylorjeva formula

## Izrek o inverzni in implicitni funkciji

## Prosi in vezani ekstremi

# Dvojni in mnogotermni integrali

## Pogoj za eskistenco

## Uvedba novih spremenljivk

## Računanje in uporaba
